# Generated by Django 5.2.1 on 2025-05-27 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StampCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('stamps_needed', models.PositiveIntegerField(default=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('is_redeemed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'stampcard',
            },
        ),
        migrations.CreateModel(
            name='StampEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('stamp_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='api.stampcard')),
            ],
            options={
                'db_table': 'stampentry',
            },
        ),
    ]
