# Generated by Django 5.2.1 on 2025-06-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_add_initial_stampcard_and_stampentry_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stampentry',
            name='notes',
        ),
        migrations.AddField(
            model_name='stampcard',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
